### ISSUE TITLE
train.flist of CelebA

### ISSUE THREAD

**Issue by htyj123** [yingchen001/WaveFill#1]
Could you please provided the train.flist of the CelebA dataset, Thank you very much

**Comment by yingchen001** [comment]
Hi,

You may find the flist [here](https://drive.google.com/drive/folders/1T5Z0RZBY7YAYgVi1315VDYk85kU1M-SF?usp=sharing), hope it will help, thanks.

Regards,
Yingchen

**Comment by htyj123** [comment]
Thank you
