### ISSUE TITLE
Parameter settings of test_wavelet.sh

### ISSUE THREAD

**Issue by vivibyl** [yingchen001/WaveFill#2]
When testing the celeba-HQ pre-training model, I don’t know how to set the parameters in test_wavelet.sh, Thank you very much！
![image](https://user-images.githubusercontent.com/96947061/147867589-7aafb2a4-2068-490f-baf8-5ec380869747.png)
The result of my current operation is like this, I don't know why. Thank you for your review！

**Comment by yingchen001** [comment]
please check whether models.networks.generator.py to see whether the class name is correct. By right it should be _WaveletInpaintLv2GCFRANGenerator_. Thanks.
