### ISSUE TITLE
poor test results for place2 pretrained models

### ISSUE THREAD

**Issue by CodingMice** [yingchen001/WaveFill#4]
I have test celeba pretrained model, and it looks nice. However I got  poor test results for place2 pretrained models. Is something wrong?

**Comment by yingchen001** [comment]
I'm not sure how poor the results are, but it is generally because places2 are more complicated and consist of many different scenes and objects. Celebahq dataset only contains of aligned face images, so the inpainting results are more realistic. Thanks.
